In [4]:
# Shape :which means the number of the elements in each dimension
# in this we are using the shape keyword to determine the dimension of the array
import numpy as np
res=np.array([[1,2,3],[2,3,3]])
print(res.shape)
print("Dimension of the array:",res.ndim)

(2, 3)
Dimension of the array: 2


In [13]:
# creating the array with the 5 dimensions using the ndmin
import numpy as np
res=np.array([1,2,3,4] ,ndmin=5)
print(res)
print(res.shape)
print(res.ndim)


[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)
5


In [26]:
# reshape : changing the shape of the array using the reshape
import numpy as np
res=np.array([[1,2,3],[2,3,3]])
# r1=res.reshape(3,2)
r1=res.reshape(2,3)
print(r1)

[[1 2 3]
 [2 3 3]]


In [34]:
import numpy as np
res=np.arange(21)
print(res)
r1=res.reshape(7,3)
print(r1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]


In [38]:
# iterating the array using the for loop

import numpy as np
res=np.arange(21)
for i in res:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [50]:
# Sorting method in the array
import numpy as np
i=np.array([5,6,2,1])
print(i)

[5 6 2 1]


In [54]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

# arr = np.concatenate((arr1, arr2), axis=0)
arr = np.concatenate((arr1, arr2))
arr.sort()


print(arr)

# print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [57]:
# here the sort the values using the axis=0: the number of the column must match,axis=1: the number of the row must match


import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)
# arr = np.concatenate(arr1, arr2)
arr.sort()


print(arr)

# print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [62]:
import numpy as np

arr1 = np.array([[12, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)



print(arr)

[[12  2  5  6]
 [ 3  4  7  8]]


In [66]:
# eliminat duplicat names.using the unique

import numpy as np
r=np.array(['zenila','xylan','rorke','venisa','alin','bob','alin','bob','alin','bob','marley'])
s=np.unique(r)
# sort the values with the alphabets...
print(s)


['alin' 'bob' 'marley' 'rorke' 'venisa' 'xylan' 'zenila']


In [67]:
# eliminat duplicat numbers. 

import numpy as np
r=np.array([10,120,12,12,12,12,4,3,3,33,2,22,22,1,11,1,11,10,10,10,5,5,5,6,6,6,3,3,3,22,22])
s=np.unique(r)
# sort the values with the numbers...
print(s)

[  1   2   3   4   5   6  10  11  12  22  33 120]
