In [8]:
import numpy as np
r=np.arange(2,100,2)
print("odd:",r)

odd: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


In [16]:
import numpy as np
r=np.arange(10)
print(r)
# print(r[5:8])  here start from the 5 end upto 7
r[5:8]=12
# the value of the 5 to 8 index has been changed  12
print(r)
arr_slice=r[5:8]
# here storing the values from 5:8 with new value and index[1] of 99
arr_slice[1]=99
print(r)
# [:] bare slice will asssign values to the array
arr_slice[:]=64
print(r)


[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 12 12 12  8  9]
[ 0  1  2  3  4 12 99 12  8  9]
[ 0  1  2  3  4 64 64 64  8  9]


In [33]:
# will work on the 2d,3d arrays..
import numpy as np
r=np.array([[1,2,3],[4,5,6],[7,8,9]])
# print(r)
print(r.ndim)
print(r.shape)
# access the index using the slice
# print(r[2])
# print(r[0][2])
# or we can also use the ,
print(r[0,2])




2
(3, 3)
3


In [36]:
# working with the 2d and 3d
# 3x3 for 2d 3 rows and 3 columns

import numpy as np
r=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(r)
print(r.ndim)
print(r.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [43]:
# 3d: layersXrowsXcolumns
import numpy as np
r=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,12,11]]])
print(r)
print(r.ndim)
print(r.shape)
# 2X2X3 which means 2 layers ,2 rows 3 columns


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 12 11]]]
3
(2, 2, 3)


In [1]:
# boolean indexing

import numpy as np
r=np.array(['Alex','dev','suraj','sandesh','Alex','dev'])
x=[True,True,True,True,False,False]
new_arr=r[x]
print(new_arr)
# it will return only the true values...


['Alex' 'dev' 'suraj' 'sandesh']


In [7]:
import numpy as np
r=np.zeros((8,4))
for i in range(8):
    r[i]=i
    print(r[i])

[0. 0. 0. 0.]
[1. 1. 1. 1.]
[2. 2. 2. 2.]
[3. 3. 3. 3.]
[4. 4. 4. 4.]
[5. 5. 5. 5.]
[6. 6. 6. 6.]
[7. 7. 7. 7.]
