In [1]:
# Numpy is the python library used for the working the arrays.
# Numpy is also called as the numerical python.
# numpy are mainly used for the liner algebra,matrices,fourier transform
# the numpy are used introduced by in the year 2005, travis oliphant..

# to work wih numpy we need to import the numpy package
# to install the numpy library we need to use the pip install numpy..



In [2]:
# pip install numpy
# !pip install numpy

In [3]:
import numpy as np
r=np.array([1,2,3,4])
print(type(r))

<class 'numpy.ndarray'>


In [4]:
r=12.5
print(type(r))

<class 'float'>


In [5]:
# when we use the list it not handle the that much data,it is bettar to choose the numpy as it handle the wast 
# amount of the data 
# note:arange is the built in the range like it can ndarray..
import numpy as np
r=np.arange(1000000)
p=list(range(1000000))
print(r)
print(p)


[     0      1      2 ... 999997 999998 999999]


IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [6]:
# conside an example of the numpy
import numpy as np
r=np.array([[1,2,3],[4,5,10]])
print(r*r)
# square of all the values...


[[  1   4   9]
 [ 16  25 100]]


In [7]:
# to create with the array..

# creating the ndarray
# to create the we use the array function
# to find out the dimension of the we need to use the ndim
# to find out the shape we can use the shape
import numpy as np
data=[6,7.5,8,0,1]
r=np.array(data)
print("dimension of the array(rows):",r.ndim)
print("shape of the array:",r.shape)


dimension of the array(rows): 1
shape of the array: (5,)


In [8]:
# creatting the two dimensional array
import numpy as np
r=np.array([[1,2,4],[19,23,4]])
print("Dimension of the array is(rows):",r.ndim)
print("shape of the array:",r.shape)

Dimension of the array is(rows): 2
shape of the array: (2, 3)


In [9]:
# creating the 3 d array(3X3 i,e 3 rows and the 3 columns)
import numpy as np
r=np.array([[1,2,4],[19,23,4],[12,3,4]])
print("Dimension of the array is(rows):",r.ndim)
print("shape of the array:",r.shape)

Dimension of the array is(rows): 2
shape of the array: (3, 3)


In [10]:
# like other methods of the numpy
# zeros:creating the the array with zeros
# ones:creating the the array with ones
# empty: creatin the array with empty

import numpy as np
r=np.zeros(10)
r1=np.zeros((10,4))
print(r)
print(r1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
# creating with ones
import numpy as np
r=np.ones(10)
r1=np.ones((10,4))
print(r)
print(r1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
# creating with the empty
import numpy as np
r=np.empty(10)
r1=np.empty((10,4))
print(r)
print(r1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
import numpy as np
r=np.empty((2,3,2))
print(r)


[[[1.03974073e-311 2.81617418e-322]
  [0.00000000e+000 0.00000000e+000]
  [1.44635488e-307 1.58817677e-052]]

 [[7.11819573e-091 5.99520915e-066]
  [8.26440405e-072 9.41708875e-047]
  [6.48224659e+170 4.93432906e+257]]]


In [14]:
# airthematic using the arrays...
import numpy as np
r=np.array([[1,2,4],[19,23,4]])
print("Addition:",r+r,end="")


print("Substraction:",r-r,end="")



print("Multiplication:",r*r,end="")


print("Division:",r/r,end="")


print("romving the fractional part..",r//r,end="")

Addition: [[ 2  4  8]
 [38 46  8]]Substraction: [[0 0 0]
 [0 0 0]]Multiplication: [[  1   4  16]
 [361 529  16]]Division: [[1. 1. 1.]
 [1. 1. 1.]]romving the fractional part.. [[1 1 1]
 [1 1 1]]

In [15]:
# numpy - Datatypes
# to find the datatype we are using the (dtype)..



import numpy as np
r=np.array([1,2,3,4])
s=np.array(["a","c","d"])
r1=np.array([1.3,2.5,3.5,4.6])
print(r.dtype)
print(s.dtype)
print(r1.dtype)

int64
<U1
float64


In [16]:
# creating the arrays with defined datatypes
import numpy as np
r=np.array([1,2,3,4],dtype='S')
print(r)

[b'1' b'2' b'3' b'4']


In [17]:
# converting the float to integer,int to float,float to string
# here using the method astype
import numpy as np
r=np.array([1.2,2.4,3.4,4.5])
new_arr=r.astype('i');
print(new_arr)
p=new_arr.astype('f');
print(p)
e=new_arr.astype('S');
print(e)

[1 2 3 4]
[1. 2. 3. 4.]
[b'1' b'2' b'3' b'4']
